import * as Assets from 'assets';
const AssetList = [
    {
        name: 'dogspr',
        type: 'sprite',
        path: 'gfx/dog.png',
        spriteWidth: 24,
        spriteHeight: 18,
        marginX: 0,
        marginY: 0,
    },
    {
        name: 'health',
        type: 'sprite',
        path: 'gfx/health.png',
        spriteWidth: 16,
        spriteHeight: 16,
        marginX: 0,
        marginY: 0,
    },
    {
        name: 'sign',
        type: 'sprite',
        path: 'gfx/sign.png',
        spriteWidth: 15,
        spriteHeight: 14,
        marginX: 0,
        marginY: 0,
    },
    {
        name: 'checkpoint',
        type: 'sprite',
        path: 'gfx/checkpoint.png',
        spriteWidth: 32,
        spriteHeight: 32,
        marginX: 0,
        marginY: 0,
    },
    {
        type: 'sprite',
        name: 'coin',
        path: 'gfx/coin.png',
        marginX: 0,
        marginY: 0,
        spriteWidth: 14,
        spriteHeight: 14,
    },
    {
        name: 'blueFont',
        type: 'bitmapfont',
        path: 'gfx/panicbomber_blue.png',
        glyphs: ' !"#$%&\'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~',
        glyphWidth: 8,
        charSpacing: 0,
        spaceWidth: 8,
        lineHeight: 8,
    },
    {
        type: 'sprite',
        name: 'spring',
        path: 'gfx/spring.png',
        marginX: 0,
        marginY: 0,
        spriteWidth: 16,
        spriteHeight: 16,
    },
    {
        type: 'sprite',
        name: 'bird',
        path: 'gfx/bird.png',
        marginX: 0,
        marginY: 0,
        spriteWidth: 16,
        spriteHeight: 16,
    },
    {
        type: 'sprite',
        name: 'slime',
        path: 'gfx/slime.png',
        marginX: 0,
        marginY: 0,
        spriteWidth: 16,
        spriteHeight: 16,
    },
    {
        type: 'sprite',
        name: 'bub',
        path: 'gfx/bub.png',
        marginX: 0,
        marginY: 0,
        spriteWidth: 16,
        spriteHeight: 16,
    },
    {
        type: 'sprite',
        name: 'spikeybub',
        path: 'gfx/spikeybub.png',
        marginX: 0,
        marginY: 0,
        spriteWidth: 16,
        spriteHeight: 16,
    },
    {
        type: 'sprite',
        name: 'charginbub',
        path: 'gfx/charginbub.png',
        marginX: 0,
        marginY: 0,
        spriteWidth: 16,
        spriteHeight: 16,
    },
    {
        type: 'sprite',
        name: 'ghost',
        path: 'gfx/ghost.png',
        marginX: 0,
        marginY: 0,
        spriteWidth: 18,
        spriteHeight: 16,
    },
    {
        type: 'sprite',
        name: 'puff',
        path: 'gfx/puff.png',
        marginX: 0,
        marginY: 0,
        spriteWidth: 16,
        spriteHeight: 16,
    },
    {
        type: 'sprite',
        name: 'hermit',
        path: 'gfx/hermit.png',
        marginX: 0,
        marginY: 0,
        spriteWidth: 19,
        spriteHeight: 13,
    },
    {
        type: 'sprite',
        name: 'launcher',
        path: 'gfx/launcher.png',
        marginX: 0,
        marginY: 0,
        spriteWidth: 16,
        spriteHeight: 16,
    },
    {
        type: 'sprite',
        name: 'flame',
        path: 'gfx/flame.png',
        marginX: 0,
        marginY: 0,
        spriteWidth: 14,
        spriteHeight: 47,
    },
    {
        type: 'sprite',
        name: 'flamethrower',
        path: 'gfx/flamethrower.png',
        marginX: 0,
        marginY: 0,
        spriteWidth: 16,
        spriteHeight: 16,
    },
    {
        type: 'sprite',
        name: 'crumblingblock',
        path: 'gfx/crumblingblock.png',
        marginX: 0,
        marginY: 0,
        spriteWidth: 16,
        spriteHeight: 16,
    },
    {
        type: 'sprite',
        name: 'balloon',
        path: 'gfx/balloon.png',
        marginX: 0,
        marginY: 0,
        spriteWidth: 14,
        spriteHeight: 28,
    },
    {
        type: 'sprite',
        name: 'owl',
        path: 'gfx/owl.png',
        marginX: 0,
        marginY: 0,
        spriteWidth: 21,
        spriteHeight: 19,
    },
    {
        type: 'sprite',
        name: 'blobby',
        path: 'gfx/blobby.png',
        marginX: 0,
        marginY: 0,
        spriteWidth: 16,
        spriteHeight: 16,
    },
    {
        type: 'sprite',
        name: 'daikon',
        path: 'gfx/daikon.png',
        marginX: 0,
        marginY: 0,
        spriteWidth: 16,
        spriteHeight: 19,
    },
    {
        type: 'sprite',
        name: 'totem',
        path: 'gfx/totem.png',
        marginX: 0,
        marginY: 0,
        spriteWidth: 16,
        spriteHeight: 22,
    },
    {
        type: 'sprite',
        name: 'levelend',
        path: 'gfx/bone.png',
        marginX: 0,
        marginY: 0,
        spriteWidth: 32,
        spriteHeight: 32,
    },
];
function loadAllAssets() {
    for (const asset of AssetList) {
        Assets.load(asset);
    }
}
export default loadAllAssets;
